Second attempt for fixing unittests

diff --git a/.github/workflows/ci.yaml b/.github/workflows/ci.yaml
--- a/.github/workflows/ci.yaml
+++ b/.github/workflows/ci.yaml
@@ -57,11 +57,9 @@ jobs:
       - name: Start minikube
         run: |
           sudo minikube start --vm-driver=none
-          sudo minikube update-context
-          sudo kubectl apply -k k8s/minikube -n default || echo "Skipping on Istio error"
-          sudo bash ci/wait_gordo_controller.sh
-          sudo cp -R /root/.kube /root/.minikube $HOME
-          sudo chown -R $USER $HOME/.kube $HOME/.minikube
+          minikube update-context
+          kubectl apply -k k8s/minikube -n default || echo "Skipping on Istio error"
+          bash ci/wait_gordo_controller.sh
 
       - name: Test CRDs
         run: |
